import { NextRequest, NextResponse } from 'next/server';

export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const email = searchParams.get('email') || 'ranga.niyogen@gmail.com';
    
    // Generate a verification token (in real system, this would be generated by backend)
    const verificationToken = `verify_${Date.now()}_${Math.random().toString(36).substring(2, 15)}`;
    
    // Get the frontend URL
    const baseUrl = process.env.NEXT_PUBLIC_APP_URL || 'http://localhost:3000';
    const verificationUrl = `${baseUrl}/verify-email?token=${verificationToken}`;
    
    console.log(`🔗 Generated verification link for ${email}:`);
    console.log(`📧 Email: ${email}`);
    console.log(`🔑 Token: ${verificationToken}`);
    console.log(`🔗 Verification URL: ${verificationUrl}`);
    
    return NextResponse.json({
      message: 'Verification link generated successfully',
      email: email,
      token: verificationToken,
      verificationUrl: verificationUrl,
      instructions: {
        step1: 'Copy the verification URL below',
        step2: 'Open it in your browser',
        step3: 'This will verify your email address',
        note: 'This is a temporary solution for testing. In production, this link would be sent via email.'
      }
    });
    
  } catch (error) {
    console.error('Error generating verification link:', error);
    return NextResponse.json(
      { error: 'Failed to generate verification link' },
      { status: 500 }
    );
  }
}
